pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                  // Prompt for user input
                    input message: 'Sudah selesai menggunakan Python App? (Klik "Proceed" untuk mengakhiri)', submitter: 'user'
        
                    // Enable debugging for script execution
                    set -x
        
                    // Perform PyInstaller
                    sh 'pyinstaller --onefile sources/add2vals.py'
        
                    // Disable debugging
                    set +x
            }
            // post {
            //     success {
            //         archiveArtifacts 'dist/add2vals'
            //     }
            // }
        }
    }
}
